### ISSUE TITLE
Calculator Angles not Working

### ISSUE THREAD

**Issue by Nathan3-14** [Malex21/CreateBigCannons-BallisticCalculator#2]
I am using computercraft along with this in forge 1.18.2 in order to aim the cannons. It doesn't aim correclty, and misses by a significant amount of pitch.
I have sequenced gearshifts as periferals and I am running the [.rotate](https://github.com/Creators-of-Create/Create/wiki/Sequenced-Gearshift-(Peripheral)#rotateangle-modifier) method on them.
It also rotates by less than the inputed amount.
If I am doing something wrong or if it is possible to fix, it would be greatly appreciated.

Code:
```lua
-- code is not exact, becuase long names of periferals
yaw = periferals.wrap("SequenceGearshift_1")
pitch = periferals.wrap("SequenceGearshift_2")
yaw_value = 0 --value here (0-360)
pitch_value = 0 --value here (0-360)

yaw.rotate(yaw_value)
pitch.rotate(pitch_value)
```

**Comment by Malex21** [comment]
Hey ! Sorry for the late response.

Could you give an example of false input ?
I know that for some input, the calculator currently miscalculates greatly the pitch (iirc it often happens with very close targets)
but there is a fix for that in a commit by SpaceEye
I did not merge yet, but this might fix your issue.
This could also be a problem from .rotate(), as far as I know very few mechanisms let you have precise angles on your canon.

**Comment by BowBoy1** [comment]
Having issues with this as well. I'm consistently overshooting by a lot, regardless of how far the target is from the cannon.

**Comment by BowBoy1** [comment]
propellant was doubled in strength, you might wanna update the calculator to account for that

**Comment by Malex21** [comment]
It is done ! I built the new exe and added spaceeye's commit (which should fix simulated projectiles not hitting target when still going up)

**Comment by Malex21** [comment]
Hello again ! I'm gonna close this issue (i will assume the lack of response means that you have found a solution to your problem)
Please re-open if I shouldn't close this tho
